#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import os.path
import sys

COLUMN_WIDTH = 16
MAX_COLUMNS = 5

def white(s):
  return "\033[1;37m" + s + "\033[0m"

def green(s):
  return "\033[1;32m" + s + "\033[0m"

def blue(s):
  return "\033[1;34m" + s + "\033[0m"

def gray(s):
  return "\033[1;30m" + s + "\033[0m"

def red(s):
  return "\033[1;31m" + s + "\033[0m"

def py3check():
  if sys.version_info < (3, 0):
    sys.stdout.write(red("WARNING: Use Python 3.x or later or the formatting will be all wrong!\n"))

def col(dirname):
  column = []
  dirnames = os.listdir(dirname)
  dirnames.sort()
  for fn in dirnames:
    fullname = os.path.join(dirname, fn)
    decoration = "" 
    if os.path.isdir(fullname):
      decoration = os.sep
    elif os.access(fullname, os.X_OK):
      decoration = "*"
    column += ["├── " + fn + decoration]
  if column:
    column[-1] = '└' + column[-1][1:]
  return column

def listcolumns(maxlen, lines, colrange):
  colwidth = COLUMN_WIDTH
  for linenr in range(maxlen):
    line = ""
    for colnr in colrange:
      if colnr in lines:
        rows = lines[colnr]
        if len(rows) > linenr:
          field = rows[linenr]
          spaces = (colwidth - len(field)) * " "
          if len(field) >= colwidth:
            field = field[:colwidth-4] + "... "
          if " " in field:
            first, second = field.split(" ", 1)
            if second:
              if second[0] == ".":
                second = gray(second)
              elif second[-1] == os.sep:
                second = blue(second)
              elif second[-1] == "*": 
                second = green(second[:-1] + " ")
            if second:
              field = gray(first) + " " + second
            else:
              field = first
          line += field + spaces
        else:
          line += colwidth * " "
    if linenr == 0:
      line = white(line)
    if line.strip():
      print(line)

def main():
  py3check()

  curdir = '.'
  l = os.listdir(curdir)
  l.sort()

  lines = {}

  colnr = 0
  maxlen = 0
  for dirname in l:
    if os.path.isdir(dirname):
      lines[colnr] = [dirname] + col(os.path.join(curdir, dirname))
      if len(lines[colnr]) > maxlen:
        maxlen = len(lines[colnr])
      colnr += 1
  maxcol = colnr - 1

  if maxcol <= MAX_COLUMNS:
    listcolumns(maxlen, lines, range(maxcol+1))
  else:
    start = 0
    while start < maxcol:
      stop = start + MAX_COLUMNS
      if stop > maxcol:
        stop = maxcol
      listcolumns(maxlen, lines, range(start, stop+1))
      print()
      start += MAX_COLUMNS

if __name__ == "__main__":
  main()
